version: "2.1"
services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "pg"
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

#  postgres_migrations:
#    build:
#      context: .
#      dockerfile: pg_migrations.Dockerfile
#    container_name: "postgres_migrations"
#    environment:
#      POSTGRES_USER: "postgres"
#      POSTGRES_PWD: "postgres"
#      POSTGRES_HOST: "postgres"
#      POSTGRES_PORT: 5432
#      POSTGRES_DB: "pg"
#    depends_on:
#      postgres:
#        condition: service_healthy
